# Site settings
author: Cinna G
title: Student Programmer
header-img: img/home-bg.png
email: somethingfellipickeditup@gmail.com
copyright_name: Cinna G
description: > # this means to ignore newlines until "baseurl:"
  Learning How to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cinna-codes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
